module ParameterConstants

  DEFAULT_CHART_CODE = 'DEFAULT_CHART_CODE'
  DEFAULT_CAMPUS_CODE = 'DEFAULT_CAMPUS_CODE'
  DEFAULT_CAMPUS_POSTAL_CODE = 'DEFAULT_CAMPUS_POSTAL_CODE'
  DEFAULT_CAMPUS_CITY = 'DEFAULT_CAMPUS_CITY'
  DEFAULT_CAMPUS_STATE = 'DEFAULT_CAMPUS_STATE'
  DEFAULT_CAMPUS_ADDRESS = 'DEFAULT_CAMPUS_ADDRESS'
  DEFAULT_CAMPUS_TYPE_CODE = 'DEFAULT_CAMPUS_TYPE_CODE'
  DEFAULT_FISCAL_OFFICER  = 'DEFAULT_FISCAL_OFFICER'
  DEFAULT_VENDOR_NUMBER  = 'DEFAULT_VENDOR_NUMBER'

end