class GeneralLedgerBalanceLookupPage < Lookups

  element(:fiscal_year) { |b| b.frm.text_field(name: 'universityFiscalYear') }
  element(:chart_code) { |b| b.frm.text_field(name: 'chartOfAccountsCode') }
  element(:account_number) { |b| b.frm.text_field(name: 'accountNumber') }
  element(:sub_account_number) { |b| b.frm.text_field(name: 'subAccountNumber') }
  element(:object_code) { |b| b.frm.text_field(name: 'objectCode') }
  element(:sub_object_code) { |b| b.frm.text_field(name: 'subObjectCode') }
  element(:balance_type_code) { |b| b.frm.text_field(name: 'balanceTypeCode') }
  element(:object_type_code) { |b| b.frm.text_field(name: 'objectTypeCode') }
  element(:consolidation_option) { |b| b.frm.text_field(name: 'dummyBusinessObject.consolidationOption') }
  element(:amount_view_option) { |b| b.frm.text_field(name: 'dummyBusinessObject.amountViewOption') }

  element(:consolidation_option_consolidation) { |b| b.frm.radio(id: 'dummyBusinessObject.consolidationOptionConsolidation') }
  element(:consolidation_option_detail) { |b| b.frm.radio(id: 'dummyBusinessObject.consolidationOptionDetail') }
  element(:consolidation_option_exclude_sub_accounts) { |b| b.frm.radio(id: 'dummyBusinessObject.consolidationOptionExclude Sub-Accounts') }
  element(:amount_view_option_monthly) { |b| b.frm.radio(id: 'dummyBusinessObject.amountViewOptionMonthly') }
  element(:amount_view_option_accumulate) { |b| b.frm.radio(id: 'dummyBusinessObject.amountViewOptionAccumulate') }
  element(:including_pending_ledger_entry_no) { |b| b.frm.radio(id: 'dummyBusinessObject.pendingEntryOptionNo') }
  element(:including_pending_ledger_entry_approved) { |b| b.frm.radio(id: 'dummyBusinessObject.pendingEntryOptionApproved') }
  element(:including_pending_ledger_entry_all) { |b| b.frm.radio(id: 'dummyBusinessObject.pendingEntryOptionAll') }

  action(:search_fiscal_year) { |b| b.frm.button(title: 'Search Fiscal Year').click }
  action(:search_chart_code) { |b| b.frm.button(title: 'Search Chart Code').click }
  action(:search_account_number) { |b| b.frm.button(title: 'Search Account Number').click }
  action(:search_sub_account_number) { |b| b.frm.button(title: 'Search Sub-Account Number').click }
  action(:search_object_code) { |b| b.frm.button(title: 'Search Object Code').click }
  action(:search_sub_object_code) { |b| b.frm.button(title: 'Search Sub-Object Code').click }
  action(:search_balance_type_code) { |b| b.frm.button(title: 'Search Balance Type Code').click }
  action(:search_object_type_code) { |b| b.frm.button(title: 'Search Object Type Code').click }




  #element(:s) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/help.do?methodToCall=getResourceHelpText&resourceKey=lookupHelpText') }
  #element(:z) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/portal.do?methodToCall=refresh&docFormKey=88888888') }
  #
  #
  #element(:c) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=0&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=1&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:cs) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=1&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:sd) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=2&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:dsa) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=3&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:ad) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=4&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:erferga) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=5&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:weaf) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=6&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:aef) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=7&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:eawrgd) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=8&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:weaf) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=9&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #element(:awfe) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&d-16544-s=10&chartOfAccountsCode=IT&subAccountNumber=&d-16544-o=2&d-16544-p=1&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&searchResultKey=3&balanceTypeCode=CB') }
  #
  #element(:ae) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.sys.businessobject.SystemOptions&universityFiscalYear=2014&methodToCall=start') }
  #element(:gr) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Chart&methodToCall=start') }
  #element(:ae) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Account&methodToCall=start&accountNumber=G003704') }
  #element(:dsaf) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.ObjectCode&universityFiscalYear=2014&financialObjectCode=4020&methodToCall=start') }
  #element(:aegf) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.coa.businessobject.BalanceType&code=CB&methodToCall=start') }
  #
  #element(:a) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=BB&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:af) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=CB&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:das) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=01&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:sa) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=04&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:sdad) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=07&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:a) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=10&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:aerf) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=02&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:aer) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=05&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:aefw) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=08&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:aew) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=11&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:ae) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=03&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:ae) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=06&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:wrea) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=09&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:aew) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=12&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:ae) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4020&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=13&chartOfAccountsCode=IT&docFormKey=88888888') }
  #
  #element(:af) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.sys.businessobject.SystemOptions&universityFiscalYear=2014&methodToCall=start') }
  #element(:af) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Chart&methodToCall=start') }
  #element(:af) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Account&methodToCall=start&accountNumber=G003704') }
  #element(:af) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.ObjectCode&universityFiscalYear=2014&financialObjectCode=4480&methodToCall=start') }
  #element(:af) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.coa.businessobject.BalanceType&code=CB&methodToCall=start') }
  #glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&amp;financialObjectCode=4020&amp;returnLocation=portal.do&amp;lookupableImplServiceName=glEntryLookupable&amp;financialSubObjectCode=&amp;dummyBusinessObject.pendingEntryOption=No&amp;methodToCall=search&amp;accountNumber=G003704&amp;universityFiscalYear=2014&amp;subAccountNumber=&amp;financialObjectTypeCode=&amp;financialBalanceTypeCode=CB&amp;inquiryFlag=true&amp;universityFiscalPeriodCode=01&amp;chartOfAccountsCode=IT&amp;docFormKey=88888888
  #action(:four_four_eighty) { |fiscal_period_code='BB', obj_code='4480', acct_num='G003704', bal_type_cd='CB',fisc_yr='2014',chart_o_acct='IT', b| b.frm.link(href: "https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=#{obj_code}{&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=#{acct_num}&universityFiscalYear=#{fisc_yr}&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=#{bal_type_cd}&inquiryFlag=true&universityFiscalPeriodCode=#{fiscal_period_code}&chartOfAccountsCode=#{chart_o_acct}&docFormKey=88888888") }
  ##fiscal_period_codes = []BB, CB, 01, 04,07,10,02,05,08,11,03,06,09,12,13]
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=CB&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=01&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=04&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=07&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=10&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=02&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=05&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=08&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=11&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=03&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=06&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=09&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=12&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=4480&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=13&chartOfAccountsCode=IT&docFormKey=88888888') }
  #
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.sys.businessobject.SystemOptions&universityFiscalYear=2014&methodToCall=start') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Chart&methodToCall=start') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Account&methodToCall=start&accountNumber=G003704') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.ObjectCode&universityFiscalYear=2014&financialObjectCode=6510&methodToCall=start') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.coa.businessobject.BalanceType&code=CB&methodToCall=start') }
  #
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=BB&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=CB&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=01&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=04&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=07&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=10&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=02&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=05&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=08&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=11&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=03&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=06&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=09&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=12&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6510&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=13&chartOfAccountsCode=IT&docFormKey=88888888') }
  #
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.sys.businessobject.SystemOptions&universityFiscalYear=2014&methodToCall=start') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Chart&methodToCall=start') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.Account&methodToCall=start&accountNumber=G003704') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?chartOfAccountsCode=IT&businessObjectClassName=org.kuali.kfs.coa.businessobject.ObjectCode&universityFiscalYear=2014&financialObjectCode=6540&methodToCall=start') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/kr/inquiry.do?businessObjectClassName=org.kuali.kfs.coa.businessobject.BalanceType&code=CB&methodToCall=start') }
  #
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=BB&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=CB&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=01&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=04&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=07&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=10&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=02&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=05&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=08&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=11&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=03&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=06&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=09&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=12&chartOfAccountsCode=IT&docFormKey=88888888') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glModifiedInquiry.do?businessObjectClassName=org.kuali.kfs.gl.businessobject.Entry&financialObjectCode=6540&returnLocation=portal.do&lookupableImplServiceName=glEntryLookupable&financialSubObjectCode=&dummyBusinessObject.pendingEntryOption=No&methodToCall=search&accountNumber=G003704&universityFiscalYear=2014&subAccountNumber=&financialObjectTypeCode=&financialBalanceTypeCode=CB&inquiryFlag=true&universityFiscalPeriodCode=13&chartOfAccountsCode=IT&docFormKey=88888888') }
  #
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&d-16544-e=1&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&chartOfAccountsCode=IT&subAccountNumber=&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&6578706f7274=1&searchResultKey=3&balanceTypeCode=CB') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&d-16544-e=2&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&chartOfAccountsCode=IT&subAccountNumber=&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&6578706f7274=1&searchResultKey=3&balanceTypeCode=CB') }
  #element(:) { |b| b.frm.link(href: 'https://kfs-ci.kuali.cornell.edu/kfs/glBalanceInquiry.do?formKey=88888888&businessObjectClassName=org.kuali.kfs.gl.businessobject.Balance&objectCode=&conversionFields=&tabStatesSize=18&d-16544-e=3&accountNumber=G003704&universityFiscalYear=2014&dummyBusinessObject.pendingEntryOption=No&actionEditablePropertiesGuid=9e919e1b-3712-4b30-bcfb-f19f9d1a50d9&subObjectCode=&chartOfAccountsCode=IT&subAccountNumber=&dummyBusinessObject.consolidationOption=Consolidation&methodToCall.search.y=0&lookupableImplServiceName=glBalanceLookupable&methodToCall.search.x=0&backLocation=portal.do&methodToCall=viewResults&hideReturnLink=Yes&objectTypeCode=&dummyBusinessObject.amountViewOption=Monthly&reqSearchResultsSize=4&6578706f7274=1&searchResultKey=3&balanceTypeCode=CB') }

end
